syntax = "proto3";

package brigade.cloud.v1;

option go_package = "brigade/internal/gen/cloud/v1";

// BrigadeCloudService provides a way to talk to brigade server
service BrigadeCloudService {
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse) {}
  rpc Events(EventsRequest) returns (EventsResponse) {}
  rpc Logs(LogsRequest) returns (LogsResponse) {}
}

message Payload {
  string sentence = 1;
}

message HeartbeatRequest {
  Payload payload = 1;
}

message HeartbeatResponse {
  Payload payload = 1;
}

message LogsRequest {
  string sentence = 1;
}

message LogsResponse {
  string sentence = 1;
}

message EventsRequest {
  string sentence = 1;
}

message EventsResponse {
  string sentence = 1;
}
