syntax = "proto3";

package brigade.cloud.v1;

option go_package = "brigade/internal/gen/cloud/v1";

// BrigadeCloudService provides a way to talk to brigade server
service BrigadeCloudService {
  rpc Subscribe(stream SubscribeRequest) returns (stream SubscribeResponse) {}
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse) {}
  rpc Events(EventsRequest) returns (EventsResponse) {}
  rpc Logs(LogsRequest) returns (LogsResponse) {}
}

message SubscribeRequest {
  RequestType request_type = 1;
  Payload payload = 2;
}

message TaskRequest {
  Payload payload = 1;
}

message RequestType {
  enum Type {
    TASK = 0;
  }
  Type type = 1;
}

message Payload {
  oneof event_data {
    TaskRequest task = 2;
  }
}

message SubscribeResponse {
  RequestType request_type = 1;
  Payload payload = 2;
}

message HeartbeatRequest {
  Payload payload = 1;
}

message HeartbeatResponse {
  Payload payload = 1;
}

message LogsRequest {
  string sentence = 1;
}

message LogsResponse {
  string sentence = 1;
}

message EventsRequest {
  string sentence = 1;
}

message EventsResponse {
  string sentence = 1;
}

message StatusRequest {
  string sentence = 1;
}

message StatusResponse {
  string sentence = 1;
}
